### ISSUE TITLE
Todo list before 1.0

### ISSUE THREAD

**Issue by SpikyPillow** [SpikyPillow/autocrop#1]
things left to do before 1.0:
   - [ ] app icon
   - [ ] metadata ?
   - [ ] separate thread native-dialogues, one at a time only
   - [ ] generate a json file
   - [ ] separate thread for cropping, have a ui display for it (percentage overlaying the crop button )
   - [ ] support webp as input/output
   - [ ] support jpeg/jpg as input
   - [x] readme
